# Generated by Django 4.2.18 on 2025-03-13 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cheatersheet", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "key",
                    models.CharField(
                        help_text="Unique alphanumeric student id",
                        max_length=64,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(help_text="Student name", max_length=255)),
                (
                    "student_id",
                    models.CharField(help_text="Student number", max_length=255),
                ),
                ("aplus_id", models.CharField(help_text="A+ user id", max_length=255)),
            ],
        ),
        migrations.AlterModelManagers(
            name="course",
            managers=[],
        ),
        migrations.AddField(
            model_name="case",
            name="student",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="cheatersheet.student",
            ),
        ),
    ]
