# Generated by Django 4.2.18 on 2025-03-13 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cheatersheet", "0002_student_alter_course_managers_case_student"),
    ]

    operations = [
        migrations.AlterField(
            model_name="case",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="cheatersheet.student"
            ),
        ),
    ]
