# Generated by Django 4.2.18 on 2025-03-17 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cheatersheet", "0004_alter_student_student_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="case",
            name="data_blocks",
            field=models.JSONField(default=dict, help_text="Data blocks for the case"),
        ),
    ]
