# Generated by Django 4.2.18 on 2025-03-17 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cheatersheet", "0005_case_data_blocks"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="case",
            name="data_blocks",
        ),
        migrations.CreateModel(
            name="DataBlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        help_text="Unique alphanumeric data block id",
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "data_type",
                    models.CharField(
                        help_text="Type of the data block", max_length=256
                    ),
                ),
                (
                    "data",
                    models.JSONField(default=dict, help_text="Data for the data block"),
                ),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cheatersheet.case",
                    ),
                ),
            ],
        ),
    ]
